# Generated by Django 4.2.30 on 2026-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_buildermentorjoin_user_userprofile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildermentorjoin',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='buildermentorjoin',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_role',
            field=models.CharField(choices=[('none', 'None'), ('builder', 'Builder'), ('mentor', 'Mentor'), ('both', 'Builder & Mentor')], default='none', help_text='Set automatically when an application is approved by admin.', max_length=10, verbose_name='Builder/Mentor Tag'),
        ),
    ]
