# Generated by Django 4.2.30 on 2026-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_buildermentorjoin_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_accepting_work',
            field=models.BooleanField(default=True, help_text='Builder availability toggle.', verbose_name='Accepting Work'),
        ),
    ]
