# Generated by Django 4.2.30 on 2026-05-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_is_accepting_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedBuilder',
            fields=[
            ],
            options={
                'verbose_name': 'Builder',
                'verbose_name_plural': 'Builders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userprofile',),
        ),
        migrations.CreateModel(
            name='ApprovedMentor',
            fields=[
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.userprofile',),
        ),
    ]
